services:
  content-admin:
    build:
      context: .
      args:
        VITE_ASSET_SERVER_URL: http://lynn2:3002
    container_name: asset-admin
    ports:
      - "8085:80"
    restart: unless-stopped
